version: "3"
services:
  database:
    image: mongo:4.0
    container_name: mongo-db
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3.8.9-management
    volumes:
      - ./data:/var/lib/rabbitmq:rw
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    ports:
      - 5672:5672
      - 15672:15672